### ISSUE TITLE
길찾기가 두개인데 어떤게 열릴지 예측이 안됩니다

### ISSUE THREAD

**Issue by ChangJoo-Park** [9bow/Seoul-MatZip-2019#1]
![image](https://user-images.githubusercontent.com/1451365/57054576-4fd70600-6cd0-11e9-87f8-e69321d9ca3a.png)

어떻게 생각하시나요 :donggong:

빨간색이라 카카오맵 / 티맵이 열릴거라는걸 추측해볼 수 있지만.......... (__ )

**Comment by 9bow** [comment]
네, 억지스럽지만... 카테고리가 선택 안 된 상태(= 주변 맛집 보기 모드)에서 지도 끝 부분의 마커 선택 시 지도 이동 이벤트가 발생하여 팝업이 자동으로 닫히는 버그를 임시로 막아두기 위해 사용하였건 꼼수였습니다;
어싸인이 되어 있으시네요 ( __)

**Comment by 9bow** [comment]
필요하실 것 같아 만들어봤습니다 ( __)

**Comment by ChangJoo-Park** [comment]
화이팅이라니... 흥이 절로 나네요

**Comment by ChangJoo-Park** [comment]
https://github.com/9bow/Seoul-MatZip-2019/commit/0fa6015e1078f4b543a9ec6663ff6e8ecb6df4d8#diff-3dd78fb4cc10ba91d2b64de9a195b0d5L171

이 부분에서 카카오 길찾기 -> 길찾기, Tmap 길찾기 -> 길찾기 인 부분이 둘다 길찾기인데

카카오맵, 티맵으로 표시하는게 더 좋을 것 같습니다
뭐가 열릴지 예측이 안되는 문제가 있어서요

그리고, 모바일 브라우저의 경우에 앱 url scheme을 열 수 있지만 데스크탑에서는 불가능하므로 
데스크탑의 경우에는 카카오맵을 엽니다 (_ _)

**Comment by ChangJoo-Park** [comment]
@9bow PR한다는게 그냥 마스터에 넣는 참사가 일어났네요
확인해보신후에 이상하면 저한테 뭐라고 해주세요 :see:
괜찮으면 이 이슈를 닫아주세요

**Comment by 9bow** [comment]
티맵이 뭔가 손해보는 느낌이지만 눌러보니 느낌이 괜찮아서 닫습니다 :see:
